---

image: "reporunner/archlinux"
checkout_dir: /go/src/github.com/Luzifer/ots

commands:
  # Dependencies for downloading libraries
  - pacman -Syy --noconfirm awk curl git go make nodejs-lts-fermium npm tar unzip which zip
  - make publish

environment:
  CGO_ENABLED: 0
  DRAFT: "false"
  GOPATH: /go
