name: pr-test

on:
  push: {}
  workflow_dispatch: {}

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    runs-on: forgejo

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/ots/ots

      - name: Initialize Go Workspace
        run: |
          go work init
          find . -name 'go.mod' | xargs dirname | xargs go work use

      - name: Run golangci-lint
        run: |
          golangci-lint run $(go list -f "{{.Dir}}/..." -m)

      - name: Run go test
        run: |
          go list -m | xargs go test -v -cover

      - name: Generate (and validate) translations
        run: make translate

      - name: Do a quick local build
        run: make build-local

      - name: Execute Trivy scan
        run: make trivy
