name: SBOM Scan

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  sbom-scan:
    runs-on: forgejo

    steps:
      - uses: Luzifer/actions/dependencytrack-scan@543959a4a97b64ad302d8bbcf07f46a3036e1e1d # develop
        with:
          token: ${{ secrets.DT_TOKEN }}
          url: https://dt.hub.luzifer.io
