name: SBOM Scan

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  sbom-scan:
    runs-on: forgejo

    steps:
      - uses: Luzifer/actions/dependencytrack-scan@ec4b20851e8c71c469406bbf5f25d8af685cc779 # develop
        with:
          token: ${{ secrets.DT_TOKEN }}
          url: https://dt.hub.luzifer.io
