/*
 *
 * ⚠️ This file is automatically generated, do not edit directly! ⚠️
 *
 */

const switchFormal = (formal, informal) => window.useFormalLanguage ? formal : informal

export default {
{{- range $lang, $translation := .Translations }}
  // Translation: {{ $lang }} - {{ printf "%.2f" (mul .Completion 100) }}%
  {{- if lt .Completion 1.0 }}
  // ⚠️ Language omitted because it is incomplete - if you can help translate, see pinned issue
  {{- else }}
{{- if .FormalTranslations }}
  '{{ $lang }}': switchFormal(
    {{ mustMergeOverwrite (dict) .Translations .FormalTranslations | mustToJson }},
    {{ .Translations | mustToJson }},
  ),
{{- else }}
  '{{ $lang }}': {{ .Translations | mustToJson }},
{{- end -}}
{{- end -}}
{{- end }}
}
