name: build-translate-util

on:
  push:
    branches: ['master']
    paths: ['ci/translate/**']
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-translate-util:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:cbaa72d18216f9acb448a556af646c8f02305ebd94b3a0776113507fac3d8610
      env:
        CGO_ENABLED: 0
        GOPATH: /go
        SOURCE_DATE_EPOCH: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/ots/ots

      - name: Build translate utility
        working-directory: ./ci/translate
        run: |
          go build \
            -buildvcs=false \
            -ldflags='-s -w -buildid=' \
            -o ../../translate \
            -trimpath \
            .

      - name: Log into registry
        run: oras login ghcr.io -u "${{ github.actor }}" --password-stdin <<<"${{ secrets.GITHUB_TOKEN }}"

      - name: Publish translate utility
        run: |
          oras push \
            ghcr.io/luzifer/ots/translate-util:latest \
            --artifact-type application/vnd.luzifer.ots.translate-util \
            translate:application/octet-stream
