name: build-translate-util

on:
  push:
    branches: ['master']
    paths: ['ci/translate/**']
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-translate-util:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:e9c1ce7a5538ad3afa3e7efd4450e27a1010835d7434f85029bc58ee43642ccd
      env:
        CGO_ENABLED: 0
        GOPATH: /go
        SOURCE_DATE_EPOCH: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          show-progress: false

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/ots/ots

      - name: Build translate utility
        working-directory: ./ci/translate
        run: |
          go build \
            -buildvcs=false \
            -ldflags='-s -w -buildid=' \
            -o ../../translate \
            -trimpath \
            .

      - name: Log into registry
        run: oras login ghcr.io -u "${{ github.actor }}" --password-stdin <<<"${{ secrets.GITHUB_TOKEN }}"

      - name: Publish translate utility
        run: |
          oras push \
            ghcr.io/luzifer/ots/translate-util:latest \
            --artifact-type application/vnd.luzifer.ots.translate-util \
            translate:application/octet-stream
