name: docker-publish

on:
  push:
    branches: ['master']
    tags: ['v*']

jobs:
  docker-publish:
    uses: docker/github-builder/.github/workflows/build.yml@58cb9f5b71b1836d6f690c1e95effdeb9b98cb8a # v1.17.0
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      fail-fast: true
      sbom: true
      sign: 'true'
      meta-images: ghcr.io/${{ github.repository }}
      meta-flavor: |
        latest=false
      meta-tags: |
        type=raw,value=develop,enable=${{ github.ref == 'refs/heads/master' }}
        type=ref,event=tag
        type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
