---
name: test-and-build
on:
  push:
    branches: ['**']
    tags: ['v*']

permissions:
  contents: write
  issues: write

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:2539b418c38b69856f9f0a34de0110b6fb23dc425cf1ddcb3f00add2ca5f916c
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/ots/ots

      - name: Initialize Go Workspace
        run: |
          go work init
          find . -name 'go.mod' | xargs dirname | xargs go work use

      - name: Run golangci-lint
        run: |
          golangci-lint run $(go list -f "{{.Dir}}/..." -m)

      - name: Run go test
        run: |
          go list -m | xargs go test -v -cover

      - name: Fetch translation utility
        run: |
          oras pull ${TRANSLATE_IMG}
          chmod +x translate
        env:
          TRANSLATE_IMG: ghcr.io/luzifer/ots/translate-util:latest@sha256:e51e1a80d9d56c0dd9e8e74290003f2f47e4e0e7f09cbc9c23485f3c09dc73c7

      - name: Generate (and validate) translations
        run: ./translate --write-issue-file

      - name: Delete issue template when no languages require translation
        run: |
          grep -q "### Language" translate-issue.md || rm -f translate-issue.md

      - name: Update Translations Issue
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        if: github.ref == 'refs/heads/master' && hashFiles('translate-issue.md') != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: translate-issue.md
          update_existing: true

      - name: Build release
        run: make publish
        env:
          FORCE_SKIP_UPLOAD: 'true'
          MOD_MODE: readonly
          NO_TESTS: 'true'
          PACKAGES: '.'

      - name: Execute Trivy scan
        run: make trivy

      - name: Extract changelog
        run: 'awk "/^#/ && ++c==2{exit}; /^#/f" "History.md" | tail -n +2 >release_changelog.md'

      - name: Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: '.build/*'
          bodyFile: release_changelog.md
          draft: false
          generateReleaseNotes: false
